// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID              uuid.UUID          `json:"id"`
	CityID          uuid.UUID          `json:"city_id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	Category        string             `json:"category"`
	EstimatedCost   pgtype.Numeric     `json:"estimated_cost"`
	DurationMinutes *int32             `json:"duration_minutes"`
	ImageUrl        *string            `json:"image_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type City struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Country         string             `json:"country"`
	Region          *string            `json:"region"`
	CostIndex       pgtype.Numeric     `json:"cost_index"`
	PopularityScore *int32             `json:"popularity_score"`
	Latitude        pgtype.Numeric     `json:"latitude"`
	Longitude       pgtype.Numeric     `json:"longitude"`
	Description     *string            `json:"description"`
	ImageUrl        *string            `json:"image_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SavedDestination struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CityID    uuid.UUID          `json:"city_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Trip struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Name          string             `json:"name"`
	Description   *string            `json:"description"`
	StartDate     pgtype.Date        `json:"start_date"`
	EndDate       pgtype.Date        `json:"end_date"`
	CoverPhotoUrl *string            `json:"cover_photo_url"`
	IsPublic      *bool              `json:"is_public"`
	PublicSlug    *string            `json:"public_slug"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TripActivity struct {
	ID            uuid.UUID          `json:"id"`
	TripStopID    uuid.UUID          `json:"trip_stop_id"`
	ActivityID    uuid.UUID          `json:"activity_id"`
	ScheduledDate pgtype.Date        `json:"scheduled_date"`
	ScheduledTime pgtype.Time        `json:"scheduled_time"`
	ActualCost    pgtype.Numeric     `json:"actual_cost"`
	Notes         *string            `json:"notes"`
	ActivityOrder *int32             `json:"activity_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TripExpense struct {
	ID          uuid.UUID          `json:"id"`
	TripID      uuid.UUID          `json:"trip_id"`
	TripStopID  pgtype.UUID        `json:"trip_stop_id"`
	ExpenseType string             `json:"expense_type"`
	Amount      pgtype.Numeric     `json:"amount"`
	Currency    *string            `json:"currency"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TripShare struct {
	ID               uuid.UUID          `json:"id"`
	TripID           uuid.UUID          `json:"trip_id"`
	SharedWithUserID pgtype.UUID        `json:"shared_with_user_id"`
	PermissionLevel  *string            `json:"permission_level"`
	ShareToken       *string            `json:"share_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TripStop struct {
	ID            uuid.UUID          `json:"id"`
	TripID        uuid.UUID          `json:"trip_id"`
	CityID        uuid.UUID          `json:"city_id"`
	ArrivalDate   pgtype.Date        `json:"arrival_date"`
	DepartureDate pgtype.Date        `json:"departure_date"`
	StopOrder     int32              `json:"stop_order"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                 uuid.UUID          `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	FullName           string             `json:"full_name"`
	ProfilePhotoUrl    *string            `json:"profile_photo_url"`
	LanguagePreference *string            `json:"language_preference"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
