// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one

INSERT INTO activities (city_id, name, description, category, estimated_cost, duration_minutes, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, city_id, name, description, category, estimated_cost, duration_minutes, image_url, created_at
`

type CreateActivityParams struct {
	CityID          uuid.UUID      `json:"city_id"`
	Name            string         `json:"name"`
	Description     *string        `json:"description"`
	Category        string         `json:"category"`
	EstimatedCost   pgtype.Numeric `json:"estimated_cost"`
	DurationMinutes *int32         `json:"duration_minutes"`
	ImageUrl        *string        `json:"image_url"`
}

// Activities --
func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.CityID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.EstimatedCost,
		arg.DurationMinutes,
		arg.ImageUrl,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.EstimatedCost,
		&i.DurationMinutes,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createCity = `-- name: CreateCity :one

INSERT INTO cities (name, country, region, cost_index, popularity_score, latitude, longitude, description, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, country, region, cost_index, popularity_score, latitude, longitude, description, image_url, created_at
`

type CreateCityParams struct {
	Name            string         `json:"name"`
	Country         string         `json:"country"`
	Region          *string        `json:"region"`
	CostIndex       pgtype.Numeric `json:"cost_index"`
	PopularityScore *int32         `json:"popularity_score"`
	Latitude        pgtype.Numeric `json:"latitude"`
	Longitude       pgtype.Numeric `json:"longitude"`
	Description     *string        `json:"description"`
	ImageUrl        *string        `json:"image_url"`
}

// Cities --
func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, createCity,
		arg.Name,
		arg.Country,
		arg.Region,
		arg.CostIndex,
		arg.PopularityScore,
		arg.Latitude,
		arg.Longitude,
		arg.Description,
		arg.ImageUrl,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.Region,
		&i.CostIndex,
		&i.PopularityScore,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createTrip = `-- name: CreateTrip :one

INSERT INTO trips (user_id, name, description, start_date, end_date, cover_photo_url, is_public, public_slug)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, description, start_date, end_date, cover_photo_url, is_public, public_slug, created_at, updated_at
`

type CreateTripParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Name          string      `json:"name"`
	Description   *string     `json:"description"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	CoverPhotoUrl *string     `json:"cover_photo_url"`
	IsPublic      *bool       `json:"is_public"`
	PublicSlug    *string     `json:"public_slug"`
}

// Trips --
func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.CoverPhotoUrl,
		arg.IsPublic,
		arg.PublicSlug,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CoverPhotoUrl,
		&i.IsPublic,
		&i.PublicSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTripActivity = `-- name: CreateTripActivity :one

INSERT INTO trip_activities (trip_stop_id, activity_id, scheduled_date, scheduled_time, actual_cost, notes, activity_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, trip_stop_id, activity_id, scheduled_date, scheduled_time, actual_cost, notes, activity_order, created_at
`

type CreateTripActivityParams struct {
	TripStopID    uuid.UUID      `json:"trip_stop_id"`
	ActivityID    uuid.UUID      `json:"activity_id"`
	ScheduledDate pgtype.Date    `json:"scheduled_date"`
	ScheduledTime pgtype.Time    `json:"scheduled_time"`
	ActualCost    pgtype.Numeric `json:"actual_cost"`
	Notes         *string        `json:"notes"`
	ActivityOrder *int32         `json:"activity_order"`
}

// Trip Activities --
func (q *Queries) CreateTripActivity(ctx context.Context, arg CreateTripActivityParams) (TripActivity, error) {
	row := q.db.QueryRow(ctx, createTripActivity,
		arg.TripStopID,
		arg.ActivityID,
		arg.ScheduledDate,
		arg.ScheduledTime,
		arg.ActualCost,
		arg.Notes,
		arg.ActivityOrder,
	)
	var i TripActivity
	err := row.Scan(
		&i.ID,
		&i.TripStopID,
		&i.ActivityID,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.ActualCost,
		&i.Notes,
		&i.ActivityOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createTripExpense = `-- name: CreateTripExpense :one

INSERT INTO trip_expenses (trip_id, trip_stop_id, expense_type, amount, currency, expense_date, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, trip_id, trip_stop_id, expense_type, amount, currency, expense_date, description, created_at
`

type CreateTripExpenseParams struct {
	TripID      uuid.UUID      `json:"trip_id"`
	TripStopID  pgtype.UUID    `json:"trip_stop_id"`
	ExpenseType string         `json:"expense_type"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    *string        `json:"currency"`
	ExpenseDate pgtype.Date    `json:"expense_date"`
	Description *string        `json:"description"`
}

// Trip Expenses --
func (q *Queries) CreateTripExpense(ctx context.Context, arg CreateTripExpenseParams) (TripExpense, error) {
	row := q.db.QueryRow(ctx, createTripExpense,
		arg.TripID,
		arg.TripStopID,
		arg.ExpenseType,
		arg.Amount,
		arg.Currency,
		arg.ExpenseDate,
		arg.Description,
	)
	var i TripExpense
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.TripStopID,
		&i.ExpenseType,
		&i.Amount,
		&i.Currency,
		&i.ExpenseDate,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createTripShare = `-- name: CreateTripShare :one

INSERT INTO trip_shares (trip_id, shared_with_user_id, permission_level, share_token)
VALUES ($1, $2, $3, $4)
RETURNING id, trip_id, shared_with_user_id, permission_level, share_token, created_at
`

type CreateTripShareParams struct {
	TripID           uuid.UUID   `json:"trip_id"`
	SharedWithUserID pgtype.UUID `json:"shared_with_user_id"`
	PermissionLevel  *string     `json:"permission_level"`
	ShareToken       *string     `json:"share_token"`
}

// Trip Shares --
func (q *Queries) CreateTripShare(ctx context.Context, arg CreateTripShareParams) (TripShare, error) {
	row := q.db.QueryRow(ctx, createTripShare,
		arg.TripID,
		arg.SharedWithUserID,
		arg.PermissionLevel,
		arg.ShareToken,
	)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.SharedWithUserID,
		&i.PermissionLevel,
		&i.ShareToken,
		&i.CreatedAt,
	)
	return i, err
}

const createTripStop = `-- name: CreateTripStop :one

INSERT INTO trip_stops (trip_id, city_id, arrival_date, departure_date, stop_order, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, trip_id, city_id, arrival_date, departure_date, stop_order, notes, created_at
`

type CreateTripStopParams struct {
	TripID        uuid.UUID   `json:"trip_id"`
	CityID        uuid.UUID   `json:"city_id"`
	ArrivalDate   pgtype.Date `json:"arrival_date"`
	DepartureDate pgtype.Date `json:"departure_date"`
	StopOrder     int32       `json:"stop_order"`
	Notes         *string     `json:"notes"`
}

// Trip Stops --
func (q *Queries) CreateTripStop(ctx context.Context, arg CreateTripStopParams) (TripStop, error) {
	row := q.db.QueryRow(ctx, createTripStop,
		arg.TripID,
		arg.CityID,
		arg.ArrivalDate,
		arg.DepartureDate,
		arg.StopOrder,
		arg.Notes,
	)
	var i TripStop
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CityID,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.StopOrder,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash, full_name, profile_photo_url)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, full_name, profile_photo_url, language_preference, created_at, updated_at
`

type CreateUserParams struct {
	Email           string  `json:"email"`
	PasswordHash    string  `json:"password_hash"`
	FullName        string  `json:"full_name"`
	ProfilePhotoUrl *string `json:"profile_photo_url"`
}

// queries.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.ProfilePhotoUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.LanguagePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips WHERE id = $1
`

func (q *Queries) DeleteTrip(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrip, id)
	return err
}

const deleteTripActivity = `-- name: DeleteTripActivity :exec
DELETE FROM trip_activities WHERE id = $1
`

func (q *Queries) DeleteTripActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTripActivity, id)
	return err
}

const deleteTripExpense = `-- name: DeleteTripExpense :exec
DELETE FROM trip_expenses WHERE id = $1
`

func (q *Queries) DeleteTripExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTripExpense, id)
	return err
}

const deleteTripShare = `-- name: DeleteTripShare :exec
DELETE FROM trip_shares WHERE id = $1
`

func (q *Queries) DeleteTripShare(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTripShare, id)
	return err
}

const deleteTripStop = `-- name: DeleteTripStop :exec
DELETE FROM trip_stops WHERE id = $1
`

func (q *Queries) DeleteTripStop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTripStop, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getActivitiesByCategory = `-- name: GetActivitiesByCategory :many
SELECT id, city_id, name, description, category, estimated_cost, duration_minutes, image_url, created_at FROM activities
WHERE city_id = $1 AND category = $2
ORDER BY estimated_cost ASC
`

type GetActivitiesByCategoryParams struct {
	CityID   uuid.UUID `json:"city_id"`
	Category string    `json:"category"`
}

func (q *Queries) GetActivitiesByCategory(ctx context.Context, arg GetActivitiesByCategoryParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, getActivitiesByCategory, arg.CityID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.CityID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.EstimatedCost,
			&i.DurationMinutes,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivitiesByCity = `-- name: GetActivitiesByCity :many
SELECT id, city_id, name, description, category, estimated_cost, duration_minutes, image_url, created_at FROM activities
WHERE city_id = $1
ORDER BY estimated_cost ASC, name ASC
`

func (q *Queries) GetActivitiesByCity(ctx context.Context, cityID uuid.UUID) ([]Activity, error) {
	rows, err := q.db.Query(ctx, getActivitiesByCity, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.CityID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.EstimatedCost,
			&i.DurationMinutes,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityByID = `-- name: GetActivityByID :one
SELECT id, city_id, name, description, category, estimated_cost, duration_minutes, image_url, created_at FROM activities
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetActivityByID(ctx context.Context, id uuid.UUID) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivityByID, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.EstimatedCost,
		&i.DurationMinutes,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getCitiesByCountry = `-- name: GetCitiesByCountry :many
SELECT id, name, country, region, cost_index, popularity_score, latitude, longitude, description, image_url, created_at FROM cities
WHERE country = $1
ORDER BY popularity_score DESC, name ASC
`

func (q *Queries) GetCitiesByCountry(ctx context.Context, country string) ([]City, error) {
	rows, err := q.db.Query(ctx, getCitiesByCountry, country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.Region,
			&i.CostIndex,
			&i.PopularityScore,
			&i.Latitude,
			&i.Longitude,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCityByID = `-- name: GetCityByID :one
SELECT id, name, country, region, cost_index, popularity_score, latitude, longitude, description, image_url, created_at FROM cities
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCityByID(ctx context.Context, id uuid.UUID) (City, error) {
	row := q.db.QueryRow(ctx, getCityByID, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.Region,
		&i.CostIndex,
		&i.PopularityScore,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getPopularCities = `-- name: GetPopularCities :many
SELECT id, name, country, region, cost_index, popularity_score, latitude, longitude, description, image_url, created_at FROM cities
ORDER BY popularity_score DESC
LIMIT $1
`

func (q *Queries) GetPopularCities(ctx context.Context, limit int32) ([]City, error) {
	rows, err := q.db.Query(ctx, getPopularCities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.Region,
			&i.CostIndex,
			&i.PopularityScore,
			&i.Latitude,
			&i.Longitude,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularCitiesStats = `-- name: GetPopularCitiesStats :many
SELECT 
    c.id,
    c.name,
    c.country,
    COUNT(DISTINCT ts.trip_id) as trip_count,
    COUNT(DISTINCT t.user_id) as unique_visitors
FROM cities c
JOIN trip_stops ts ON c.id = ts.city_id
JOIN trips t ON ts.trip_id = t.id
GROUP BY c.id, c.name, c.country
ORDER BY trip_count DESC
LIMIT $1
`

type GetPopularCitiesStatsRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Country        string    `json:"country"`
	TripCount      int64     `json:"trip_count"`
	UniqueVisitors int64     `json:"unique_visitors"`
}

func (q *Queries) GetPopularCitiesStats(ctx context.Context, limit int32) ([]GetPopularCitiesStatsRow, error) {
	rows, err := q.db.Query(ctx, getPopularCitiesStats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPopularCitiesStatsRow{}
	for rows.Next() {
		var i GetPopularCitiesStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.TripCount,
			&i.UniqueVisitors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedDestinations = `-- name: GetSavedDestinations :many
SELECT sd.id, sd.user_id, sd.city_id, sd.created_at, c.name, c.country, c.cost_index, c.image_url
FROM saved_destinations sd
JOIN cities c ON sd.city_id = c.id
WHERE sd.user_id = $1
ORDER BY sd.created_at DESC
`

type GetSavedDestinationsRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CityID    uuid.UUID          `json:"city_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Name      string             `json:"name"`
	Country   string             `json:"country"`
	CostIndex pgtype.Numeric     `json:"cost_index"`
	ImageUrl  *string            `json:"image_url"`
}

func (q *Queries) GetSavedDestinations(ctx context.Context, userID uuid.UUID) ([]GetSavedDestinationsRow, error) {
	rows, err := q.db.Query(ctx, getSavedDestinations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSavedDestinationsRow{}
	for rows.Next() {
		var i GetSavedDestinationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CityID,
			&i.CreatedAt,
			&i.Name,
			&i.Country,
			&i.CostIndex,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripActivitiesByDate = `-- name: GetTripActivitiesByDate :many
SELECT ta.id, ta.trip_stop_id, ta.activity_id, ta.scheduled_date, ta.scheduled_time, ta.actual_cost, ta.notes, ta.activity_order, ta.created_at, a.name as activity_name, a.description, a.category, a.estimated_cost
FROM trip_activities ta
JOIN activities a ON ta.activity_id = a.id
JOIN trip_stops ts ON ta.trip_stop_id = ts.id
WHERE ts.trip_id = $1 AND ta.scheduled_date = $2
ORDER BY ta.scheduled_time ASC, ta.activity_order ASC
`

type GetTripActivitiesByDateParams struct {
	TripID        uuid.UUID   `json:"trip_id"`
	ScheduledDate pgtype.Date `json:"scheduled_date"`
}

type GetTripActivitiesByDateRow struct {
	ID            uuid.UUID          `json:"id"`
	TripStopID    uuid.UUID          `json:"trip_stop_id"`
	ActivityID    uuid.UUID          `json:"activity_id"`
	ScheduledDate pgtype.Date        `json:"scheduled_date"`
	ScheduledTime pgtype.Time        `json:"scheduled_time"`
	ActualCost    pgtype.Numeric     `json:"actual_cost"`
	Notes         *string            `json:"notes"`
	ActivityOrder *int32             `json:"activity_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ActivityName  string             `json:"activity_name"`
	Description   *string            `json:"description"`
	Category      string             `json:"category"`
	EstimatedCost pgtype.Numeric     `json:"estimated_cost"`
}

func (q *Queries) GetTripActivitiesByDate(ctx context.Context, arg GetTripActivitiesByDateParams) ([]GetTripActivitiesByDateRow, error) {
	rows, err := q.db.Query(ctx, getTripActivitiesByDate, arg.TripID, arg.ScheduledDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTripActivitiesByDateRow{}
	for rows.Next() {
		var i GetTripActivitiesByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.TripStopID,
			&i.ActivityID,
			&i.ScheduledDate,
			&i.ScheduledTime,
			&i.ActualCost,
			&i.Notes,
			&i.ActivityOrder,
			&i.CreatedAt,
			&i.ActivityName,
			&i.Description,
			&i.Category,
			&i.EstimatedCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripActivitiesByStop = `-- name: GetTripActivitiesByStop :many
SELECT ta.id, ta.trip_stop_id, ta.activity_id, ta.scheduled_date, ta.scheduled_time, ta.actual_cost, ta.notes, ta.activity_order, ta.created_at, a.name as activity_name, a.description, a.category, a.estimated_cost, a.duration_minutes, a.image_url
FROM trip_activities ta
JOIN activities a ON ta.activity_id = a.id
WHERE ta.trip_stop_id = $1
ORDER BY ta.scheduled_date ASC, ta.activity_order ASC
`

type GetTripActivitiesByStopRow struct {
	ID              uuid.UUID          `json:"id"`
	TripStopID      uuid.UUID          `json:"trip_stop_id"`
	ActivityID      uuid.UUID          `json:"activity_id"`
	ScheduledDate   pgtype.Date        `json:"scheduled_date"`
	ScheduledTime   pgtype.Time        `json:"scheduled_time"`
	ActualCost      pgtype.Numeric     `json:"actual_cost"`
	Notes           *string            `json:"notes"`
	ActivityOrder   *int32             `json:"activity_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ActivityName    string             `json:"activity_name"`
	Description     *string            `json:"description"`
	Category        string             `json:"category"`
	EstimatedCost   pgtype.Numeric     `json:"estimated_cost"`
	DurationMinutes *int32             `json:"duration_minutes"`
	ImageUrl        *string            `json:"image_url"`
}

func (q *Queries) GetTripActivitiesByStop(ctx context.Context, tripStopID uuid.UUID) ([]GetTripActivitiesByStopRow, error) {
	rows, err := q.db.Query(ctx, getTripActivitiesByStop, tripStopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTripActivitiesByStopRow{}
	for rows.Next() {
		var i GetTripActivitiesByStopRow
		if err := rows.Scan(
			&i.ID,
			&i.TripStopID,
			&i.ActivityID,
			&i.ScheduledDate,
			&i.ScheduledTime,
			&i.ActualCost,
			&i.Notes,
			&i.ActivityOrder,
			&i.CreatedAt,
			&i.ActivityName,
			&i.Description,
			&i.Category,
			&i.EstimatedCost,
			&i.DurationMinutes,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripActivitiesCost = `-- name: GetTripActivitiesCost :one
SELECT 
    ts.trip_id,
    SUM(COALESCE(ta.actual_cost, a.estimated_cost, 0)) as total_activities_cost,
    COUNT(ta.id) as activity_count
FROM trip_activities ta
JOIN activities a ON ta.activity_id = a.id
JOIN trip_stops ts ON ta.trip_stop_id = ts.id
WHERE ts.trip_id = $1
GROUP BY ts.trip_id
`

type GetTripActivitiesCostRow struct {
	TripID              uuid.UUID `json:"trip_id"`
	TotalActivitiesCost int64     `json:"total_activities_cost"`
	ActivityCount       int64     `json:"activity_count"`
}

func (q *Queries) GetTripActivitiesCost(ctx context.Context, tripID uuid.UUID) (GetTripActivitiesCostRow, error) {
	row := q.db.QueryRow(ctx, getTripActivitiesCost, tripID)
	var i GetTripActivitiesCostRow
	err := row.Scan(&i.TripID, &i.TotalActivitiesCost, &i.ActivityCount)
	return i, err
}

const getTripActivityByID = `-- name: GetTripActivityByID :one
SELECT id, trip_stop_id, activity_id, scheduled_date, scheduled_time, actual_cost, notes, activity_order, created_at FROM trip_activities
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTripActivityByID(ctx context.Context, id uuid.UUID) (TripActivity, error) {
	row := q.db.QueryRow(ctx, getTripActivityByID, id)
	var i TripActivity
	err := row.Scan(
		&i.ID,
		&i.TripStopID,
		&i.ActivityID,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.ActualCost,
		&i.Notes,
		&i.ActivityOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getTripBudgetSummary = `-- name: GetTripBudgetSummary :one
SELECT 
    trip_id,
    SUM(CASE WHEN expense_type = 'transport' THEN amount ELSE 0 END) as transport_total,
    SUM(CASE WHEN expense_type = 'accommodation' THEN amount ELSE 0 END) as accommodation_total,
    SUM(CASE WHEN expense_type = 'meals' THEN amount ELSE 0 END) as meals_total,
    SUM(CASE WHEN expense_type = 'other' THEN amount ELSE 0 END) as other_total,
    SUM(amount) as total_expenses,
    COUNT(*) as expense_count
FROM trip_expenses
WHERE trip_id = $1
GROUP BY trip_id
`

type GetTripBudgetSummaryRow struct {
	TripID             uuid.UUID `json:"trip_id"`
	TransportTotal     int64     `json:"transport_total"`
	AccommodationTotal int64     `json:"accommodation_total"`
	MealsTotal         int64     `json:"meals_total"`
	OtherTotal         int64     `json:"other_total"`
	TotalExpenses      int64     `json:"total_expenses"`
	ExpenseCount       int64     `json:"expense_count"`
}

func (q *Queries) GetTripBudgetSummary(ctx context.Context, tripID uuid.UUID) (GetTripBudgetSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTripBudgetSummary, tripID)
	var i GetTripBudgetSummaryRow
	err := row.Scan(
		&i.TripID,
		&i.TransportTotal,
		&i.AccommodationTotal,
		&i.MealsTotal,
		&i.OtherTotal,
		&i.TotalExpenses,
		&i.ExpenseCount,
	)
	return i, err
}

const getTripByID = `-- name: GetTripByID :one
SELECT id, user_id, name, description, start_date, end_date, cover_photo_url, is_public, public_slug, created_at, updated_at FROM trips
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTripByID(ctx context.Context, id uuid.UUID) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByID, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CoverPhotoUrl,
		&i.IsPublic,
		&i.PublicSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripByPublicSlug = `-- name: GetTripByPublicSlug :one
SELECT id, user_id, name, description, start_date, end_date, cover_photo_url, is_public, public_slug, created_at, updated_at FROM trips
WHERE public_slug = $1 AND is_public = true
LIMIT 1
`

func (q *Queries) GetTripByPublicSlug(ctx context.Context, publicSlug *string) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByPublicSlug, publicSlug)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CoverPhotoUrl,
		&i.IsPublic,
		&i.PublicSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripExpenses = `-- name: GetTripExpenses :many
SELECT id, trip_id, trip_stop_id, expense_type, amount, currency, expense_date, description, created_at FROM trip_expenses
WHERE trip_id = $1
ORDER BY expense_date DESC, created_at DESC
`

func (q *Queries) GetTripExpenses(ctx context.Context, tripID uuid.UUID) ([]TripExpense, error) {
	rows, err := q.db.Query(ctx, getTripExpenses, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripExpense{}
	for rows.Next() {
		var i TripExpense
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.TripStopID,
			&i.ExpenseType,
			&i.Amount,
			&i.Currency,
			&i.ExpenseDate,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripExpensesByType = `-- name: GetTripExpensesByType :many
SELECT id, trip_id, trip_stop_id, expense_type, amount, currency, expense_date, description, created_at FROM trip_expenses
WHERE trip_id = $1 AND expense_type = $2
ORDER BY expense_date DESC
`

type GetTripExpensesByTypeParams struct {
	TripID      uuid.UUID `json:"trip_id"`
	ExpenseType string    `json:"expense_type"`
}

func (q *Queries) GetTripExpensesByType(ctx context.Context, arg GetTripExpensesByTypeParams) ([]TripExpense, error) {
	rows, err := q.db.Query(ctx, getTripExpensesByType, arg.TripID, arg.ExpenseType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripExpense{}
	for rows.Next() {
		var i TripExpense
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.TripStopID,
			&i.ExpenseType,
			&i.Amount,
			&i.Currency,
			&i.ExpenseDate,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripShareByToken = `-- name: GetTripShareByToken :one
SELECT id, trip_id, shared_with_user_id, permission_level, share_token, created_at FROM trip_shares
WHERE share_token = $1
LIMIT 1
`

func (q *Queries) GetTripShareByToken(ctx context.Context, shareToken *string) (TripShare, error) {
	row := q.db.QueryRow(ctx, getTripShareByToken, shareToken)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.SharedWithUserID,
		&i.PermissionLevel,
		&i.ShareToken,
		&i.CreatedAt,
	)
	return i, err
}

const getTripSharesByTrip = `-- name: GetTripSharesByTrip :many
SELECT ts.id, ts.trip_id, ts.shared_with_user_id, ts.permission_level, ts.share_token, ts.created_at, u.email, u.full_name
FROM trip_shares ts
LEFT JOIN users u ON ts.shared_with_user_id = u.id
WHERE ts.trip_id = $1
`

type GetTripSharesByTripRow struct {
	ID               uuid.UUID          `json:"id"`
	TripID           uuid.UUID          `json:"trip_id"`
	SharedWithUserID pgtype.UUID        `json:"shared_with_user_id"`
	PermissionLevel  *string            `json:"permission_level"`
	ShareToken       *string            `json:"share_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Email            *string            `json:"email"`
	FullName         *string            `json:"full_name"`
}

func (q *Queries) GetTripSharesByTrip(ctx context.Context, tripID uuid.UUID) ([]GetTripSharesByTripRow, error) {
	rows, err := q.db.Query(ctx, getTripSharesByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTripSharesByTripRow{}
	for rows.Next() {
		var i GetTripSharesByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.SharedWithUserID,
			&i.PermissionLevel,
			&i.ShareToken,
			&i.CreatedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripStats = `-- name: GetTripStats :one

SELECT 
    COUNT(DISTINCT t.id) as total_trips,
    COUNT(DISTINCT t.user_id) as unique_users,
    COUNT(DISTINCT ts.city_id) as unique_cities_visited,
    AVG(DATE_PART('day', t.end_date - t.start_date) + 1) as avg_trip_duration_days
FROM trips t
LEFT JOIN trip_stops ts ON t.id = ts.trip_id
`

type GetTripStatsRow struct {
	TotalTrips          int64   `json:"total_trips"`
	UniqueUsers         int64   `json:"unique_users"`
	UniqueCitiesVisited int64   `json:"unique_cities_visited"`
	AvgTripDurationDays float64 `json:"avg_trip_duration_days"`
}

// Analytics (Optional) --
func (q *Queries) GetTripStats(ctx context.Context) (GetTripStatsRow, error) {
	row := q.db.QueryRow(ctx, getTripStats)
	var i GetTripStatsRow
	err := row.Scan(
		&i.TotalTrips,
		&i.UniqueUsers,
		&i.UniqueCitiesVisited,
		&i.AvgTripDurationDays,
	)
	return i, err
}

const getTripStopByID = `-- name: GetTripStopByID :one
SELECT ts.id, ts.trip_id, ts.city_id, ts.arrival_date, ts.departure_date, ts.stop_order, ts.notes, ts.created_at, c.name as city_name, c.country
FROM trip_stops ts
JOIN cities c ON ts.city_id = c.id
WHERE ts.id = $1
LIMIT 1
`

type GetTripStopByIDRow struct {
	ID            uuid.UUID          `json:"id"`
	TripID        uuid.UUID          `json:"trip_id"`
	CityID        uuid.UUID          `json:"city_id"`
	ArrivalDate   pgtype.Date        `json:"arrival_date"`
	DepartureDate pgtype.Date        `json:"departure_date"`
	StopOrder     int32              `json:"stop_order"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CityName      string             `json:"city_name"`
	Country       string             `json:"country"`
}

func (q *Queries) GetTripStopByID(ctx context.Context, id uuid.UUID) (GetTripStopByIDRow, error) {
	row := q.db.QueryRow(ctx, getTripStopByID, id)
	var i GetTripStopByIDRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CityID,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.StopOrder,
		&i.Notes,
		&i.CreatedAt,
		&i.CityName,
		&i.Country,
	)
	return i, err
}

const getTripStops = `-- name: GetTripStops :many
SELECT ts.id, ts.trip_id, ts.city_id, ts.arrival_date, ts.departure_date, ts.stop_order, ts.notes, ts.created_at, c.name as city_name, c.country, c.cost_index, c.image_url as city_image
FROM trip_stops ts
JOIN cities c ON ts.city_id = c.id
WHERE ts.trip_id = $1
ORDER BY ts.stop_order ASC
`

type GetTripStopsRow struct {
	ID            uuid.UUID          `json:"id"`
	TripID        uuid.UUID          `json:"trip_id"`
	CityID        uuid.UUID          `json:"city_id"`
	ArrivalDate   pgtype.Date        `json:"arrival_date"`
	DepartureDate pgtype.Date        `json:"departure_date"`
	StopOrder     int32              `json:"stop_order"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CityName      string             `json:"city_name"`
	Country       string             `json:"country"`
	CostIndex     pgtype.Numeric     `json:"cost_index"`
	CityImage     *string            `json:"city_image"`
}

func (q *Queries) GetTripStops(ctx context.Context, tripID uuid.UUID) ([]GetTripStopsRow, error) {
	rows, err := q.db.Query(ctx, getTripStops, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTripStopsRow{}
	for rows.Next() {
		var i GetTripStopsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.CityID,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.StopOrder,
			&i.Notes,
			&i.CreatedAt,
			&i.CityName,
			&i.Country,
			&i.CostIndex,
			&i.CityImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingTrips = `-- name: GetUpcomingTrips :many
SELECT id, user_id, name, description, start_date, end_date, cover_photo_url, is_public, public_slug, created_at, updated_at FROM trips
WHERE user_id = $1 AND start_date >= CURRENT_DATE
ORDER BY start_date ASC
LIMIT $2
`

type GetUpcomingTripsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetUpcomingTrips(ctx context.Context, arg GetUpcomingTripsParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, getUpcomingTrips, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.CoverPhotoUrl,
			&i.IsPublic,
			&i.PublicSlug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, profile_photo_url, language_preference, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.LanguagePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, profile_photo_url, language_preference, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.LanguagePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTrips = `-- name: GetUserTrips :many
SELECT id, user_id, name, description, start_date, end_date, cover_photo_url, is_public, public_slug, created_at, updated_at FROM trips
WHERE user_id = $1
ORDER BY start_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserTripsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetUserTrips(ctx context.Context, arg GetUserTripsParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, getUserTrips, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.CoverPhotoUrl,
			&i.IsPublic,
			&i.PublicSlug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderTripStops = `-- name: ReorderTripStops :exec
UPDATE trip_stops
SET stop_order = $2
WHERE id = $1
`

type ReorderTripStopsParams struct {
	ID        uuid.UUID `json:"id"`
	StopOrder int32     `json:"stop_order"`
}

func (q *Queries) ReorderTripStops(ctx context.Context, arg ReorderTripStopsParams) error {
	_, err := q.db.Exec(ctx, reorderTripStops, arg.ID, arg.StopOrder)
	return err
}

const saveDestination = `-- name: SaveDestination :one

INSERT INTO saved_destinations (user_id, city_id)
VALUES ($1, $2)
ON CONFLICT (user_id, city_id) DO NOTHING
RETURNING id, user_id, city_id, created_at
`

type SaveDestinationParams struct {
	UserID uuid.UUID `json:"user_id"`
	CityID uuid.UUID `json:"city_id"`
}

// Saved Destinations --
func (q *Queries) SaveDestination(ctx context.Context, arg SaveDestinationParams) (SavedDestination, error) {
	row := q.db.QueryRow(ctx, saveDestination, arg.UserID, arg.CityID)
	var i SavedDestination
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CityID,
		&i.CreatedAt,
	)
	return i, err
}

const searchActivities = `-- name: SearchActivities :many
SELECT a.id, a.city_id, a.name, a.description, a.category, a.estimated_cost, a.duration_minutes, a.image_url, a.created_at FROM activities a
JOIN cities c ON a.city_id = c.id
WHERE (a.name ILIKE '%' || $1 || '%' OR a.description ILIKE '%' || $1 || '%')
  AND ($4::uuid IS NULL OR a.city_id = $4::uuid)
  AND ($5::text IS NULL OR a.category = $5::text)
ORDER BY a.estimated_cost ASC
LIMIT $2 OFFSET $3
`

type SearchActivitiesParams struct {
	Column1  *string     `json:"column_1"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	CityID   pgtype.UUID `json:"city_id"`
	Category *string     `json:"category"`
}

func (q *Queries) SearchActivities(ctx context.Context, arg SearchActivitiesParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, searchActivities,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.CityID,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.CityID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.EstimatedCost,
			&i.DurationMinutes,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCities = `-- name: SearchCities :many
SELECT id, name, country, region, cost_index, popularity_score, latitude, longitude, description, image_url, created_at FROM cities
WHERE (name ILIKE '%' || $1 || '%' OR country ILIKE '%' || $1 || '%')
ORDER BY popularity_score DESC, name ASC
LIMIT $2 OFFSET $3
`

type SearchCitiesParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) SearchCities(ctx context.Context, arg SearchCitiesParams) ([]City, error) {
	rows, err := q.db.Query(ctx, searchCities, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.Region,
			&i.CostIndex,
			&i.PopularityScore,
			&i.Latitude,
			&i.Longitude,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsaveDestination = `-- name: UnsaveDestination :exec
DELETE FROM saved_destinations
WHERE user_id = $1 AND city_id = $2
`

type UnsaveDestinationParams struct {
	UserID uuid.UUID `json:"user_id"`
	CityID uuid.UUID `json:"city_id"`
}

func (q *Queries) UnsaveDestination(ctx context.Context, arg UnsaveDestinationParams) error {
	_, err := q.db.Exec(ctx, unsaveDestination, arg.UserID, arg.CityID)
	return err
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    cover_photo_url = COALESCE($6, cover_photo_url),
    is_public = COALESCE($7, is_public),
    public_slug = COALESCE($8, public_slug)
WHERE id = $1
RETURNING id, user_id, name, description, start_date, end_date, cover_photo_url, is_public, public_slug, created_at, updated_at
`

type UpdateTripParams struct {
	ID            uuid.UUID   `json:"id"`
	Name          *string     `json:"name"`
	Description   *string     `json:"description"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	CoverPhotoUrl *string     `json:"cover_photo_url"`
	IsPublic      *bool       `json:"is_public"`
	PublicSlug    *string     `json:"public_slug"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.CoverPhotoUrl,
		arg.IsPublic,
		arg.PublicSlug,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CoverPhotoUrl,
		&i.IsPublic,
		&i.PublicSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTripActivity = `-- name: UpdateTripActivity :one
UPDATE trip_activities
SET scheduled_date = COALESCE($2, scheduled_date),
    scheduled_time = COALESCE($3, scheduled_time),
    actual_cost = COALESCE($4, actual_cost),
    notes = COALESCE($5, notes),
    activity_order = COALESCE($6, activity_order)
WHERE id = $1
RETURNING id, trip_stop_id, activity_id, scheduled_date, scheduled_time, actual_cost, notes, activity_order, created_at
`

type UpdateTripActivityParams struct {
	ID            uuid.UUID      `json:"id"`
	ScheduledDate pgtype.Date    `json:"scheduled_date"`
	ScheduledTime pgtype.Time    `json:"scheduled_time"`
	ActualCost    pgtype.Numeric `json:"actual_cost"`
	Notes         *string        `json:"notes"`
	ActivityOrder *int32         `json:"activity_order"`
}

func (q *Queries) UpdateTripActivity(ctx context.Context, arg UpdateTripActivityParams) (TripActivity, error) {
	row := q.db.QueryRow(ctx, updateTripActivity,
		arg.ID,
		arg.ScheduledDate,
		arg.ScheduledTime,
		arg.ActualCost,
		arg.Notes,
		arg.ActivityOrder,
	)
	var i TripActivity
	err := row.Scan(
		&i.ID,
		&i.TripStopID,
		&i.ActivityID,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.ActualCost,
		&i.Notes,
		&i.ActivityOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateTripStop = `-- name: UpdateTripStop :one
UPDATE trip_stops
SET arrival_date = COALESCE($2, arrival_date),
    departure_date = COALESCE($3, departure_date),
    stop_order = COALESCE($4, stop_order),
    notes = COALESCE($5, notes)
WHERE id = $1
RETURNING id, trip_id, city_id, arrival_date, departure_date, stop_order, notes, created_at
`

type UpdateTripStopParams struct {
	ID            uuid.UUID   `json:"id"`
	ArrivalDate   pgtype.Date `json:"arrival_date"`
	DepartureDate pgtype.Date `json:"departure_date"`
	StopOrder     *int32      `json:"stop_order"`
	Notes         *string     `json:"notes"`
}

func (q *Queries) UpdateTripStop(ctx context.Context, arg UpdateTripStopParams) (TripStop, error) {
	row := q.db.QueryRow(ctx, updateTripStop,
		arg.ID,
		arg.ArrivalDate,
		arg.DepartureDate,
		arg.StopOrder,
		arg.Notes,
	)
	var i TripStop
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CityID,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.StopOrder,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name = COALESCE($2, full_name),
    profile_photo_url = COALESCE($3, profile_photo_url),
    language_preference = COALESCE($4, language_preference)
WHERE id = $1
RETURNING id, email, password_hash, full_name, profile_photo_url, language_preference, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID                 uuid.UUID `json:"id"`
	FullName           *string   `json:"full_name"`
	ProfilePhotoUrl    *string   `json:"profile_photo_url"`
	LanguagePreference *string   `json:"language_preference"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.ProfilePhotoUrl,
		arg.LanguagePreference,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.LanguagePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
