// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Activities --
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	// Cities --
	CreateCity(ctx context.Context, arg CreateCityParams) (City, error)
	// Trips --
	CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error)
	// Trip Activities --
	CreateTripActivity(ctx context.Context, arg CreateTripActivityParams) (TripActivity, error)
	// Trip Expenses --
	CreateTripExpense(ctx context.Context, arg CreateTripExpenseParams) (TripExpense, error)
	// Trip Shares --
	CreateTripShare(ctx context.Context, arg CreateTripShareParams) (TripShare, error)
	// Trip Stops --
	CreateTripStop(ctx context.Context, arg CreateTripStopParams) (TripStop, error)
	// queries.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTrip(ctx context.Context, id uuid.UUID) error
	DeleteTripActivity(ctx context.Context, id uuid.UUID) error
	DeleteTripExpense(ctx context.Context, id uuid.UUID) error
	DeleteTripShare(ctx context.Context, id uuid.UUID) error
	DeleteTripStop(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetActivitiesByCategory(ctx context.Context, arg GetActivitiesByCategoryParams) ([]Activity, error)
	GetActivitiesByCity(ctx context.Context, cityID uuid.UUID) ([]Activity, error)
	GetActivityByID(ctx context.Context, id uuid.UUID) (Activity, error)
	GetCitiesByCountry(ctx context.Context, country string) ([]City, error)
	GetCityByID(ctx context.Context, id uuid.UUID) (City, error)
	GetPopularCities(ctx context.Context, limit int32) ([]City, error)
	GetPopularCitiesStats(ctx context.Context, limit int32) ([]GetPopularCitiesStatsRow, error)
	GetSavedDestinations(ctx context.Context, userID uuid.UUID) ([]GetSavedDestinationsRow, error)
	GetTripActivitiesByDate(ctx context.Context, arg GetTripActivitiesByDateParams) ([]GetTripActivitiesByDateRow, error)
	GetTripActivitiesByStop(ctx context.Context, tripStopID uuid.UUID) ([]GetTripActivitiesByStopRow, error)
	GetTripActivitiesCost(ctx context.Context, tripID uuid.UUID) (GetTripActivitiesCostRow, error)
	GetTripActivityByID(ctx context.Context, id uuid.UUID) (TripActivity, error)
	GetTripBudgetSummary(ctx context.Context, tripID uuid.UUID) (GetTripBudgetSummaryRow, error)
	GetTripByID(ctx context.Context, id uuid.UUID) (Trip, error)
	GetTripByPublicSlug(ctx context.Context, publicSlug *string) (Trip, error)
	GetTripExpenses(ctx context.Context, tripID uuid.UUID) ([]TripExpense, error)
	GetTripExpensesByType(ctx context.Context, arg GetTripExpensesByTypeParams) ([]TripExpense, error)
	GetTripShareByToken(ctx context.Context, shareToken *string) (TripShare, error)
	GetTripSharesByTrip(ctx context.Context, tripID uuid.UUID) ([]GetTripSharesByTripRow, error)
	// Analytics (Optional) --
	GetTripStats(ctx context.Context) (GetTripStatsRow, error)
	GetTripStopByID(ctx context.Context, id uuid.UUID) (GetTripStopByIDRow, error)
	GetTripStops(ctx context.Context, tripID uuid.UUID) ([]GetTripStopsRow, error)
	GetUpcomingTrips(ctx context.Context, arg GetUpcomingTripsParams) ([]Trip, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserTrips(ctx context.Context, arg GetUserTripsParams) ([]Trip, error)
	ReorderTripStops(ctx context.Context, arg ReorderTripStopsParams) error
	// Saved Destinations --
	SaveDestination(ctx context.Context, arg SaveDestinationParams) (SavedDestination, error)
	SearchActivities(ctx context.Context, arg SearchActivitiesParams) ([]Activity, error)
	SearchCities(ctx context.Context, arg SearchCitiesParams) ([]City, error)
	UnsaveDestination(ctx context.Context, arg UnsaveDestinationParams) error
	UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error)
	UpdateTripActivity(ctx context.Context, arg UpdateTripActivityParams) (TripActivity, error)
	UpdateTripStop(ctx context.Context, arg UpdateTripStopParams) (TripStop, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
